### ISSUE TITLE
How to import the customs modules in config file correctly? (Maybe bug) 

### ISSUE THREAD

**Issue by fangxu622** [open-mmlab/mim-example#5]
This is dir tree in path "xx/mim-prj/mmcls_self" which as  root folder of the project.
```
├── config
├── data
├── dataset_self
├── hook_self
├── loss
├── models
└── Res
```

In the project path:
from dataset_self import smallNORB
this line code is ok.
![image](https://user-images.githubusercontent.com/16681534/124597822-81425200-de96-11eb-940b-4d2811590c60.png)

![image](https://user-images.githubusercontent.com/16681534/124597851-8a332380-de96-11eb-8012-06421cd7ce7c.png)

![image](https://user-images.githubusercontent.com/16681534/124597876-90c19b00-de96-11eb-9772-2efc9985ab7e.png)

So ， I want to use it on config file for avoiding modifying the source file.
this line code in config file.
```
custom_imports = dict(imports=['dataset_self.smallNORB'], allow_failed_imports=False)
or 
custom_imports = dict(imports=['dataset_self.mmnorb'], allow_failed_imports=False)
```
they all are wrong when run 
```
mim train mmcls ./config/caps_norb.py
```

## another question

I want import two customs modules. how to do it ?

custom_imports = dict(imports=['customs module 1' , " customs module 2"], allow_failed_imports=False)

Is this way?

**Comment by kennymckormick** [comment]
You need to set the python path by adding `PYTHONPATH='.':$PYTHONPATH` before the command.  Please refer to other examples for details.

**Comment by fangxu622** [comment]
add the cmd  "export PYTHONPATH='.':$PYTHONPATH "

then 

![image](https://user-images.githubusercontent.com/16681534/124601761-cbc5cd80-de9a-11eb-87a9-fe404ee02259.png)

**Comment by kennymckormick** [comment]
I mean something like: `PYTHONPATH='.':$PYTHONPATH mim train mmcls ./config/caps_norb.py`. It should be in a single command.

**Comment by fangxu622** [comment]
> I mean something like: `PYTHONPATH='.':$PYTHONPATH mim train mmcls ./config/caps_norb.py`. It should be in a single command.
It‘s ok. sigle cmd should also be ok. 
we should import  [" filename.filename"] . 
thanks !
